function saveSubjectInfoToFile(height, weight, gender, samplingRate, recordingTime)
    
    data_dir = dir('*_rawTrajectories.mat');
    clear file_name_list;
    [file_name_list{1:length(data_dir)}] = deal(data_dir.name);
    sample_file_name = file_name_list{1};
    [date, subject_id] = getFileParameters(sample_file_name);


    numberOfDataPoints = samplingRate * recordingTime;
    save ...
      ( ...
        'subjectInfo', ...
        'height', ...
        'weight', ...
        'gender', ...
        'samplingRate', ...
        'recordingTime', ...
        'numberOfDataPoints', ...
        'date', ...
        'subject_id' ...
      );
end