function saveSubjectInfoToFile(height, weight, gender)
    
    data_dir = dir('*_markerTrajectories.mat');
    clear file_name_list;
    [file_name_list{1:length(data_dir)}] = deal(data_dir.name);
    sample_file_name = file_name_list{1};
    [date, subject_id] = getFileParameters(sample_file_name);


    save ...
      ( ...
        'subjectInfo', ...
        'height', ...
        'weight', ...
        'gender', ...
        'date', ...
        'subject_id' ...
      );
end