function restructureStepEvents

    data_dir = dir(['analysis' filesep '*_stepEvents.mat']);
    clear file_name_list;
    [file_name_list{1:length(data_dir)}] = deal(data_dir.name);
    number_of_files = length(file_name_list);

    for i_file = 1 : number_of_files
        load_file = ['analysis' filesep file_name_list{i_file}];
        loaded_events = load(load_file);

        events = struct;
        if isfield(loaded_events, 'ignore_times')
            events.ignore_times = loaded_events.ignore_times;
        end

        events.event_data = ...
          { ...
            loaded_events.left_pushoff_times; ...
            loaded_events.left_touchdown_times; ...
            loaded_events.right_pushoff_times; ...
            loaded_events.right_touchdown_times; ...
          };
%                 loaded_events.left_fullstance_times; ...
%                 loaded_events.right_fullstance_times; ...
        events.event_labels = ...
          { ...
            'left_pushoff'; ...
            'left_touchdown'; ...
            'right_pushoff'; ...
            'right_touchdown'; ...
          };
%                 'left_fullstance'; ...
%                 'right_fullstance' ...

        [date, subject_id, trial_type, trial_number] = getFileParameters(file_name_list{i_file});
        save_file = ['analysis' filesep makeFileName(date, subject_id, trial_type, trial_number, 'events')];
        saveDataToFile(save_file, events);
    end
        
end