%     This file is part of the CoBaL code base
%     Copyright (C) 2017 Hendrik Reimann <hendrikreimann@gmail.com>
% 
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
% 
%     You should have received a copy of the GNU General Public License
%     along with this program.  If not, see <http://www.gnu.org/licenses/>.

% this script transform raw data from ascii into matlab format

% input: 
% Experimental data files generated by e.g. Nexus, QTM, labview etc.
% Files are expected to be in subfolders named <subject code>_<source type>, e.g. XYZ_labview
% any source type is viable, but if it is not in the default list, it must be specified as a name-value pair, 
% e.g. importAscii('sources', 'someSource') would look for data in the subfolder XYZ_someSource
%
% output: 
% Files containing the same data in .mat format, with some additional information about where they came from.
% Output files will be saved to folders "raw" and "processed".

function importMot(varargin)

    parser = inputParser;
    parser.KeepUnmatched = true;
    sources_default = {['opensim' filesep 'inverseKinematics']};
    addParameter(parser, 'sources', sources_default)
    parse(parser, varargin{:})
    sources = parser.Results.sources;
    
    
    %% prepare
    current_path = pwd;
    path_split = strsplit(current_path, filesep);
    subject_code = path_split{end};

    %% import data
    
    
    for i_source = 1 : length(sources)
        source_dir = sources{i_source};
        if exist(source_dir, 'dir')
            % get list of files to import from this directory
            clear file_name_list;
            data_dir = dir([source_dir filesep '*.mot']);
            [file_name_list{1:length(data_dir)}] = deal(data_dir.name);

            % go through files and import
            number_of_files = length(file_name_list);
            for i_file = 1 : number_of_files
                % file name stuff
                data_file_name = file_name_list{i_file};
                [date, subject_id, trial_type, trial_number, file_type] = getFileParameters(data_file_name);

                number_of_header_lines = 11;

                % import data
                [imported_data, delimiter, number_of_header_lines_returned] = importdata([source_dir filesep data_file_name], '\t', number_of_header_lines);
                data_headers = imported_data.textdata(9, :);

                number_of_samples_split = strsplit(imported_data.textdata{3, 1}, '=');
                number_of_samples = str2num(number_of_samples_split{2});

                trajectories = imported_data.data(:, 2:end);
                time =imported_data.data(:, 1);
                sampling_rate = 1/median(diff(time));

                labels = data_headers(2:end);

                % directions
                number_of_trajectories = size(trajectories, 2);
                directions = cell(2, number_of_trajectories);
                [directions{:, :}] = deal('TBD');

                % save
                save_folder = 'processed';
                save_file_name = makeFileName(date, subject_id, trial_type, trial_number, 'inverseKinematics.mat');
                save ...
                  ( ...
                    [save_folder filesep save_file_name], ...
                    'trajectories', ...
                    'time', ...
                    'sampling_rate', ...
                    'labels',  ...
                    'directions' ...
                  );
                addAvailableData ...
                  ( ...
                    'trajectories', ...
                    'time', ...
                    'sampling_rate', ...
                    '_labels', ...
                    '_directions', ...
                    save_folder, ...
                    save_file_name ...
                  );


                disp(['imported ' source_dir filesep data_file_name])

            end

            disp(['imported ' num2str(number_of_files) ' files'])        

        else
            error(['Failed to locate directory ' source ' to process .mot files'])



        end
    end

end















